@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String imageTag = "v{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"

olcnePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/node-exporter:' + imageTag ): 'olcne/node-exporter:' + imageTag],
        architectures: ['x86_64', 'aarch64'],
        platforms: ['ol8'],
        publishImage: true,
        yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder']
)
