@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String imageTag = "v1.9.1"

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/1.9.1', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/node-exporter:' + imageTag ): 'olcne/node-exporter:' + imageTag],
        architectures: ['x86_64', 'aarch64'],
        platforms: ['ol9'],
        buildScript: "sh olm/build-image.sh"
)
